accounts/urls.py
from django.urls import path

from accounts import views
from .views import UserRegistrationView, LogoutView, UserLoginView, OpenCheckingAccountView, OpenSavingsAccountView

app_name = 'accounts'

urlpatterns = [
    path("", views.AccountDetailsView.as_view(), name="accounts_home"),
    path("login/", UserLoginView.as_view(), name="user_login"),
    path("logout/", LogoutView.as_view(), name="user_logout"),
    path("register/", UserRegistrationView.as_view(), name="user_registration"),

    path('open-accounts/', views.OpenAccountsView.as_view(), name='open_accounts'),

    path('open-checking-account/', OpenCheckingAccountView.as_view(), name='open_checking_account'),
    path('open-savings-account/', OpenSavingsAccountView.as_view(), name='open_savings_account'),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path

from core.views import HomeView, UserHomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home/', UserHomeView.as_view(), name='user_home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('loans/', include('loans.urls', namespace='loans')),
]

loans/urls.py
from django.urls import path

from loans import views

app_name = 'loans'

urlpatterns = [
    path('', views.LoanListView.as_view(), name='loan_home'),
    path('apply-loan', views.loan_application, name='apply_loan'),

    path('apply-personal-loan/', views.PersonalLoanCreateView.as_view(), name='apply_personal_loan'),
    path('apply-home-loan/', views.HomeLoanCreateView.as_view(), name='apply_home_loan'),
    path('apply-education-loan/', views.EducationLoanCreateView.as_view(), name='apply_education_loan'),

    path('add-university/', views.add_universities, name='add_university'),
    path('save-insurance/', views.save_insurance)
]

transactions/urls.py
from django.urls import path

from .views import DepositView, WithdrawView, TransactionListView

app_name = 'transactions'

urlpatterns = [
    path("deposit/<int:account_no>/", DepositView.as_view(), name="deposit_money"),
    path("withdraw/<int:account_no>/", WithdrawView.as_view(), name="withdraw_money"),
    path("list/<int:account_no>/", TransactionListView.as_view(), name="transaction_list")
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from decimal import Decimal
from django.db import connection

from .constants import ACCOUNT_TYPES
from .managers import UserManager


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, null=False, blank=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return 0


class UserAddress(models.Model):
    user = models.OneToOneField(
        User,
        related_name='address',
        on_delete=models.CASCADE,
    )
    street_address = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    postal_code = models.PositiveIntegerField()
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.email


# ==================================== Bank Accounts =========================================
class BankAccount(models.Model):
    user = models.ForeignKey(User, related_name='account', on_delete=models.CASCADE)
    account_no = models.BigAutoField(primary_key=True, unique=True)
    date_opened = models.DateField(default=timezone.now)
    balance = models.DecimalField(
        default=0.00,
        max_digits=12,
        decimal_places=2
    )
    account_type = models.CharField(choices=ACCOUNT_TYPES, default='CHECKING')

    @staticmethod
    def get_positive_balance_accounts():
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM accounts_bankaccount WHERE balance > 0;")
            rows = cursor.fetchall()
        return rows

class CheckingBankAccount(BankAccount):
    service_charge = models.DecimalField(
        default=10.00,
        max_digits=12,
        decimal_places=2
    )

    def deduct_service_charge(self):
        '''Deducts service charge from the account balance and returns the deducted amount.'''
        if self.balance > self.service_charge:  
            self.balance -= self.service_charge
            self.save()
            return self.service_charge
        return Decimal('0.00')


class SavingsBankAccount(BankAccount):
    interest_rate = models.DecimalField(
        default=8,
        max_digits=5,
        decimal_places=2,
        help_text="Annual interest rate in percentage"
    )

    def add_interest(self):
        '''Adds interest to the account balance based on the interest rate and returns the interest amount.'''
        
        monthly_interest_rate = self.interest_rate / 12 / 100
        interest_amount = monthly_interest_rate * self.balance
        self.balance += interest_amount
        self.save()
        return interest_amount

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import timedelta

from .constants import GENDER_CHOICE
from .models import User, UserAddress


class UserAddressForm(forms.ModelForm):
    class Meta:
        model = UserAddress
        fields = [
            'street_address',
            'city',
            'postal_code',
            'country'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 rounded '
                    'py-3 px-4 leading-tight focus:outline-none '
                    'focus:bg-white focus:border-gray-500'
                )
            })

def validate_age(value):
    """ Validator to check if age is at least 18 years """
    today = timezone.now().date()
    age_18 = today - timedelta(days=18*365.25)  # Approximation including leap years
    if value > age_18:
        raise ValidationError("Customer must be at least 18 years old.")

class UserRegistrationForm(UserCreationForm):
    gender = forms.ChoiceField(choices=GENDER_CHOICE)
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), validators=[validate_age])
    first_name = forms.CharField(widget=forms.TextInput(attrs={'autofocus': 'on'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'autofocus': 'off'}))

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 '
                    'rounded py-3 px-4 leading-tight '
                    'focus:outline-none focus:bg-white '
                    'focus:border-gray-500'
                )
            })

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.gender = self.cleaned_data.get('gender')
        user.birth_date = self.cleaned_data.get('birth_date')
        user.email = self.cleaned_data.get('email')
        if commit:
            
            user.save()
            
        return user


class UserUpdateForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), validators=[validate_age])
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'birth_date']  # Customize fields based on your User model
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'})
        }

accounts/views.py
import logging

from django.contrib import messages
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db import transaction
from django.shortcuts import HttpResponseRedirect, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.db import connection
from django.views.generic import TemplateView, RedirectView, View, UpdateView, DeleteView

from .forms import UserRegistrationForm, UserAddressForm
from .models import CheckingBankAccount, SavingsBankAccount
from .models import CheckingBankAccount
from .forms import UserUpdateForm 

logger = logging.getLogger(__name__)
User = get_user_model()


class UserRegistrationView(TemplateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'accounts/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(
                reverse_lazy('user_home')
            )
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        registration_form = UserRegistrationForm(self.request.POST)
        address_form = UserAddressForm(self.request.POST)

        if registration_form.is_valid() and address_form.is_valid():
            user = registration_form.save()
            address = address_form.save(commit=False)
            address.user = user
            address.save()

            login(self.request, user)
            messages.success(
                self.request,
                (
                    # f'Thank You For Creating A Bank Account. '
                    # f'Your Account Number is {user.account.account_no}. '
                    'Thank You for registering with us!'
                )
            )
            return HttpResponseRedirect(
                reverse_lazy('user_home')
            )

        return self.render_to_response(
            self.get_context_data(
                registration_form=registration_form,
                address_form=address_form
            )
        )

    def get_context_data(self, **kwargs):
        if 'registration_form' not in kwargs:
            kwargs['registration_form'] = UserRegistrationForm()
        if 'address_form' not in kwargs:
            kwargs['address_form'] = UserAddressForm()

        return super().get_context_data(**kwargs)


class UserLoginView(LoginView):
    template_name = 'accounts/user_login.html'
    redirect_authenticated_user = False


class LogoutView(RedirectView):
    pattern_name = 'home'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/update_user.html'
    success_url = reverse_lazy('user_home')  # Redirect to the user profile or home page after update

    def get_object(self, queryset=None):
        return self.request.user  # Return the current user, do not fetch from URL

    def form_valid(self, form):
        messages.success(self.request, 'Your profile has been updated successfully.')
        return super().form_valid(form)

# ======================================== Checking Accounts Views ======================================
@method_decorator(login_required, name='dispatch')
class OpenAccountsView(TemplateView):
    template_name = 'accounts/open_accounts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # You can add more context variables if needed
        return context


class OpenCheckingAccountView(LoginRequiredMixin, View):
    template_name = 'accounts/open_checking_accounts.html'

    def get(self, request, *args, **kwargs):
        existing_account = SavingsBankAccount.objects.filter(user=request.user, account_type='SAVINGS').first()

        if existing_account:
            # If an account exists, inform the user and redirect
            messages.info(request, "You already have a checking account.")
            return redirect(reverse_lazy('accounts:accounts_home'))

        with transaction.atomic():
            # Create the checking account with default values
            account = CheckingBankAccount(
                user=request.user,
                date_opened=timezone.now(),
                balance=0.00,
                service_charge=10.00,
                account_type='CHECKING'
            )
            account.save()
            logger.info("Checking account successfully created for user %s", request.user)
            return redirect(reverse_lazy(
                'accounts:accounts_home'))  
    
class DeleteCheckingAccountView(LoginRequiredMixin, DeleteView):
    model = CheckingBankAccount
    template_name = 'accounts/delete_checking_account.html'
    success_url = reverse_lazy('accounts:accounts_home')

    def get_queryset(self):
       
        return self.model.objects.filter(user=self.request.user)

    def delete(self, request, *args, **kwargs):
        messages.success(request, "Checking account deleted successfully.")
        return super().delete(request, *args, **kwargs)


# ========================================== SAVINGS ACCOUNT ==========================================

class OpenSavingsAccountView(LoginRequiredMixin, View):
    template_name = 'accounts/open_savings_account.html'

    def get(self, request, *args, **kwargs):
        existing_account = SavingsBankAccount.objects.filter(user=request.user, account_type='SAVINGS').first()

        if existing_account:
            # If an account exists, inform the user and redirect
            messages.info(request, "You already have a savings account.")
            return redirect(reverse_lazy('accounts:accounts_home'))

        with transaction.atomic():
            # Create the savings account with default values
            account = SavingsBankAccount(
                user=request.user,
                date_opened=timezone.now(),
                balance=0.00,
                interest_rate=10.00,
                account_type='SAVINGS'
            )
            account.save()
            return redirect(reverse_lazy('accounts:accounts_home'))

class DeleteSavingsAccountView(LoginRequiredMixin, DeleteView):
    model = SavingsBankAccount
    template_name = 'accounts/delete_savings_account.html'
    success_url = reverse_lazy('accounts:accounts_home')  # Redirect here after deletion

    def get_queryset(self):
        """ Ensure that a user can only delete their own savings account. """
        return self.model.objects.filter(user=self.request.user)

    def delete(self, request, *args, **kwargs):
        messages.success(request, "Savings account deleted successfully.")
        return super().delete(request, *args, **kwargs)
    
# ============================= Account Details Home Page =============================================
class AccountDetailsView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/accounts_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Assuming you have different types of accounts under the same user
        context['accounts'] = self.request.user.account.all()
        return context

templates/accounts/accounts_home.html
{% extends 'core/base.html' %}
{% load static %}

{% include 'core/messages.html' %}

{% block content %}
    <div class="container mx-auto mt-8">
        <h2 class="text-2xl font-bold mb-4">Your Accounts</h2>
        <!-- Button to open a new account -->
        <div class="mb-4">
            <a href="{% url 'accounts:open_accounts' %}"
               class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Open New Account
            </a>
        </div>
        {% if accounts %}
            {% for account in accounts %}
                <div class="bg-white shadow overflow-hidden sm:rounded-lg mb-4">
                    <div class="px-4 py-5 sm:px-6 grid grid-cols-2 gap-4">
                        <div>
                            <h3 class="text-lg leading-6 font-medium text-gray-900">{{ account.account_type }}</h3>
                            <p class="mt-1 max-w-2xl text-sm text-gray-500">Details about the account.</p>
                            <div class="border-t border-gray-200">
                                <dl>
                                    <div class="bg-gray-50 px-4 py-5 grid grid-cols-1 sm:grid-cols-2 gap-4">
                                        <div class="text-sm font-medium text-gray-500">Balance:</div>
                                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-1">
                                            ${{ account.balance }}</div>
                                        <div class="text-sm font-medium text-gray-500">Date Opened:</div>
                                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-1">{{ account.date_opened }}</div>
                                    </div>
                                    {% if account.account_type == "CHECKING" %}
                                        <div class="bg-white px-4 py-5 grid grid-cols-1 sm:grid-cols-2 gap-4">
                                            <div class="text-sm font-medium text-gray-500">Service Charge:</div>
                                            <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-1">
                                                ${{ account.checkingbankaccount.service_charge }}</div>
                                        </div>
                                    {% endif %}
                                    {% if account.account_type == "SAVINGS" %}
                                        <div class="bg-gray-50 px-4 py-5 grid grid-cols-1 sm:grid-cols-2 gap-4">
                                            <div class="text-sm font-medium text-gray-500">Interest Rate:</div>
                                            <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-1">{{ account.savingsbankaccount.interest_rate }}%</div>
                                        </div>
                                    {% endif %}
                                </dl>
                            </div>
                        </div>
                        <div class="col-span-2 sm:col-span-1">
                            <h3 class="text-lg leading-6 font-medium text-gray-900">Recent Transactions</h3>
                            <div class="mt-2 px-4 py-2 bg-gray-100 rounded-lg">
                                {% if account.account_type == "CHECKING" and account.checkingbankaccount.transactions.all|length > 0 %}
                                    <!-- Checking account transactions -->
                                    <table class="min-w-full divide-y divide-gray-200">
                                        <thead>
                                        <tr>
                                            <th class="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Date
                                            </th>
                                            <th class="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Type
                                            </th>
                                            <th class="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Amount
                                            </th>
                                            <th class="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Closing Balance
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody class="bg-white divide-y divide-gray-200">
                                        {% for transaction in account.checkingbankaccount.transactions.all|slice:":3" %}
                                            <tr>
                                                <td class="px-2 py-4 whitespace-nowrap text-sm text-gray-900">{{ transaction.timestamp }}</td>
                                                <td class="px-2 py-4 whitespace-nowrap text-sm text-gray-900">{{ transaction.transaction_type }}</td>
                                                <td class="px-2 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    ${{ transaction.amount }}</td>
                                                <td class="px-2 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    ${{ transaction.balance_after_transaction }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                {% elif account.account_type == "SAVINGS" and account.savingsbankaccount.transactions.all|length > 0 %}
                                    <!-- Savings account transactions -->
                                    <table class="min-w-full divide-y divide-gray-200">
                                        <thead>
                                        <tr>
                                            <th class="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Date
                                            </th>
                                            <th class="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Type
                                            </th>
                                            <th class="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Amount
                                            </th>
                                            <th class="px-2 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                Closing Balance
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody class="bg-white divide-y divide-gray-200">
                                        {% for transaction in account.savingsbankaccount.transactions.all|slice:":3" %}
                                            <tr>
                                                <td class="px-2 py-4 whitespace-nowrap text-sm text-gray-900">{{ transaction.timestamp }}</td>
                                                <td class="px-2 py-4 whitespace-nowrap text-sm text-gray-900">{{ transaction.transaction_type }}</td>
                                                <td class="px-2 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    ${{ transaction.amount }}</td>
                                                <td class="px-2 py-4 whitespace-nowrap text-sm text-gray-900">
                                                    ${{ transaction.balance_after_transaction }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                {% else %}
                                    <p class="text-sm text-gray-500">You do not have any transactions in this
                                        account.</p>
                                {% endif %}
                            </div>
                            <div class="mt-4 flex justify-end space-x-4">
                                <a href="{% url 'transactions:deposit_money' account_no=account.account_no %}"
                                   class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
                                    Deposit Money
                                </a>
                                <a href="{% url 'transactions:withdraw_money' account_no=account.account_no %}"
                                   class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                                    Withdraw Money
                                </a>
                                <a href="{% url 'transactions:transaction_list' account_no=account.account_no %}"
                                   class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                                    List Transactions
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="bg-white shadow overflow-hidden sm:rounded-lg p-4">
                <p>You do not have any accounts with us.</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/accounts/open_accounts.html
{% extends 'core/base.html' %}
{% load static %}

{% block head_title %}Open Account{% endblock %}

{% block content %}
    <div class="container mx-auto mt-8 p-8 bg-white rounded-lg shadow-lg">
        <h1 class="text-3xl font-bold text-gray-800 mb-6">Open a New Account</h1>
        <div class="flex flex-col md:flex-row justify-center items-center gap-6">
            <!-- Open Checking Account Button -->
            <form action="{% url 'accounts:open_checking_account' %}" method="get" class="w-full md:w-auto">
                {% csrf_token %}
                <button type="submit"
                        class="w-full md:w-auto bg-blue-600 hover:bg-blue-800 text-white font-semibold py-3 px-6 rounded-lg transition duration-300 ease-in-out shadow hover:shadow-md">
                    Open Checking Account
                </button>
            </form>

            <!-- Open Savings Account Button -->
            <form action="{% url 'accounts:open_savings_account' %}" method="get" class="w-full md:w-auto">
                {% csrf_token %}
                <button type="submit"
                        class="w-full md:w-auto bg-green-600 hover:bg-green-800 text-white font-semibold py-3 px-6 rounded-lg transition duration-300 ease-in-out shadow hover:shadow-md">
                    Open Savings Account
                </button>
            </form>
        </div>
    </div>
{% endblock %}

templates/accounts/user_login.html
{% extends 'core/base.html' %} {% load static %} {% block head_title %}Banking System{% endblock %} {% block content %}
    {% if form.non_field_errors %} {% for error in form.non_field_errors %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
            <p class="font-bold">Error!</p>
            <p class="block sm:inline">{{ error }}</p>
        </div>
    {% endfor %} {% endif %}
    <div class="grid grid-cols-3 gap-4">
        <div></div>
        <div class="py-2 px-3 rounded-xl bg-white mt-12">
            <h1 class="font-mono font-bold text-3xl text-center pb-5 shadow-md">Sign In</h1>
            <hr>
            <div class="w-full mt-10">
                <form method="post" class="shadow-md border border-gray-200 rounded px-8 pt-6 pb-8 mb-4">
                    {% csrf_token %} {% for hidden_field in form.hidden_fields %} {{ hidden_field.errors }}
                    {{ hidden_field }} {% endfor %} {% for field in form.visible_fields %}
                    <div class="mb-4">
                        <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                            {{ field.label }}
                        </label>
                        <input class="shadow appearance-none border border-gray-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                               name="{{ field.name }}" id="{{ field.id_for_label }}" type="{{ field.widget_type }}">
                    </div>
                    {% if field.errors %} {% for error in field.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %} {% endif %} {% endfor %}

                    <div class="flex items-center justify-center w-full">
                        <button class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                                type="submit">
                            Sign In
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}