banking_system/urls.py
from django.contrib import admin
from django.urls import include, path

from core.views import HomeView, UserHomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home/', UserHomeView.as_view(), name='user_home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('transactions/', include('transactions.urls', namespace='transactions')),
    path('loans/', include('loans.urls', namespace='loans')),
]

loans/urls.py
from django.urls import path

from loans import views

app_name = 'loans'

urlpatterns = [
    path('', views.LoanListView.as_view(), name='loan_home'),
    path('apply-loan', views.loan_application, name='apply_loan'),

    path('apply-personal-loan/', views.PersonalLoanCreateView.as_view(), name='apply_personal_loan'),
    path('apply-home-loan/', views.HomeLoanCreateView.as_view(), name='apply_home_loan'),
    path('apply-education-loan/', views.EducationLoanCreateView.as_view(), name='apply_education_loan'),

    path('add-university/', views.add_universities, name='add_university'),
    path('save-insurance/', views.save_insurance)
]

loans/models.py
import uuid
from decimal import Decimal

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Max
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField


# ---------------------------- Personal Loan ---------------------------------------------
class Loan(models.Model):
    class LoanStatusChoices(models.TextChoices):
        PENDING = 'Pending', 'Pending'
        APPROVED = 'Approved', 'Approved'
        DECLINED = 'Declined', 'Declined'

    LOAN_TYPES = (
        ('personal', 'Personal Loan'),
        ('home', 'Home Loan'),
        ('education', 'Education Loan')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    loan_id = models.BigAutoField(primary_key=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    emi_amount = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    interest_rate = models.DecimalField(decimal_places=2, max_digits=5, null=False, default=10)
    tenure = models.PositiveIntegerField(null=False)
    installment_paid = models.PositiveIntegerField(default=0, null=False)
    status = models.CharField(
        max_length=10,
        choices=LoanStatusChoices.choices,
        default=LoanStatusChoices.PENDING,
        null=False
    )
    loan_type = models.CharField(choices=LOAN_TYPES, max_length=10, default='personal')
    
    class Meta:
        unique_together = ('user', 'loan_type')

    def save(self, *args, **kwargs):
        self.calculate_emi()
        super().save(*args, **kwargs)

    def calculate_emi(self):
        P = self.amount
        r = self.interest_rate / Decimal('100.0') / Decimal('12.0')
        n = self.tenure

        if n > 0 and r > 0:
            emi = (P * r * (1 + r) ** n) / ((1 + r) ** n - 1)
        else:
            emi = 0

        self.emi_amount = emi.quantize(Decimal('0.01'))

    # -------------------------- Home Loan ---------------------------------------------------


class Address(models.Model):
    address_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    street = models.CharField(max_length=255, null=False, blank=False)
    city = models.CharField(max_length=100, null=False, blank=False)
    state = models.CharField(max_length=100, null=False, blank=False)
    country = models.CharField(default="United States")
    zip_code = models.CharField(max_length=10, null=False, blank=False)

    def __str__(self):
        return f"{self.street}, {self.city}, {self.state}, {self.country}, {self.zip_code}"


class Insurance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number = models.IntegerField(null=False, blank=False)
    company = models.CharField(max_length=255)
    premium = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return f"{self.company} - ${self.premium}"


# year validator
def validate_year(value):
    current_year = timezone.now().year
    if value > current_year:
        raise ValidationError(f'Year {value} is in the future.')
    if value < 1800:  # Assuming houses built before 1800 are not considered
        raise ValidationError(f'Year {value} is too far in the past.')


class HomeLoan(Loan):
    home_address = models.OneToOneField(Address, on_delete=models.CASCADE, related_name='home_loans')
    insurance = models.OneToOneField(Insurance, on_delete=models.CASCADE)
    house_built_year = models.PositiveIntegerField(validators=[validate_year])


# ------------------------------- Student Loan ---------------------------------------
class University(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # University Info
    name = models.CharField()
    code = models.IntegerField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.code:  # Check if code is not already set
            last_code = University.objects.aggregate(Max('code'))['code__max']
            self.code = last_code + 1 if last_code else 1001  # Start from 1001 if no entries exist
        super(University, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class StudentInfo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    first_name = models.CharField()
    middle_name = models.CharField(null=True)
    last_name = models.CharField()
    date_of_birth = models.DateField()
    email = models.EmailField(unique=True)
    phone = PhoneNumberField()


class EducationLoan(Loan):
    university = models.OneToOneField(University, on_delete=models.CASCADE)
    student_info = models.OneToOneField(StudentInfo, on_delete=models.CASCADE)

    graduation_date = models.DateField()
    degree = models.CharField()
    college_id = models.CharField()

    def __init__(self, *args, **kwargs):
        super(EducationLoan, self).__init__(*args, **kwargs)
        if self._state.adding:
            self.interest_rate = Decimal('8.0')

loans/views.py
import json, logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction, IntegrityError
from django.db.models import Max
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, UpdateView
from django.views.generic.edit import FormView

from .forms import LoanForm, HomeLoanForm, EducationLoanForm
from .models import Insurance, Loan, University


logger = logging.getLogger(__name__)

# ========================= Home Page for loans View ========================================
def loan_application(request):
    context = {}
    return render(request, 'loans/loans_apply.html', context)


# =========================== Personal Loan Views ===========================================
# class PersonalLoanCreateView(LoginRequiredMixin, CreateView):
#     model = Loan
#     form_class = LoanForm
#     template_name = 'loans/personal_loan_form.html'
#     success_url = reverse_lazy('loans:loan_home')  # Redirect to loan list view after a loan is successfully created

#     def get(self, request):
#         '''
#         This method is called for GET requests
#         '''
#         if request.user.is_authenticated:
#             personal_loan_form = LoanForm()
#             return render(request, self.template_name, {'personal_loan_form': personal_loan_form})

#     def form_valid(self, form):
#         '''
#         This method is called when valid form data has been posted.
#         It should return an HttpResponse.
#         '''
#         messages.success(self.request, "Personal loan application submitted successfully!")
#         with transaction.atomic():
#             form.instance.user = self.request.user
#             return super().form_valid(form)  # Saves the form instance, form.save() is called here

#     def form_invalid(self, form):
#         ''' Adding an error message '''
#         messages.error(self.request, "Error submitting the personal loan application. Please check the form.")
#         return super().form_invalid(form)

#     def get_form_kwargs(self):
#         """
#         Pass additional kwargs to the form instance. Useful for passing the request object or other variables.
#         """
#         kwargs = super(PersonalLoanCreateView, self).get_form_kwargs()
#         kwargs['user'] = self.request.user
#         return kwargs

from django.db import connection

def check_existing_loans(user_id, loan_type):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM appname_loan
                WHERE id = %s AND loan_type = %s
            )
        """, [user_id, loan_type])
        exists = cursor.fetchone()[0]
    return exists

class PersonalLoanCreateView(LoginRequiredMixin, CreateView):
    model = Loan
    form_class = LoanForm
    template_name = 'loans/personal_loan_form.html'
    success_url = reverse_lazy('loans:loan_home')  # Redirect to loan list view after a loan is successfully created

    def get(self, request):
        '''
        This method is called for GET requests
        '''
        personal_loan_form = LoanForm()
        return render(request, self.template_name, {'personal_loan_form': personal_loan_form})

    def form_valid(self, form):
        '''
        This method is called when valid form data has been posted.
        It should return an HttpResponse.
        '''
        loan_type = 'personal'
        existing_home_loans = Loan.objects.filter(user=self.request.user, loan_type=loan_type).exists()
        if existing_home_loans:
            # If an existing home loan is found, prevent the new loan application
            messages.error(self.request, "You've already taken a Personal Loan and are not eligible for another personal loan.")
            return redirect('loans:apply_personal_loan')
        
        try:
            with transaction.atomic():
                form.instance.user = self.request.user
                form.save()  # Attempt to save the form instance
                messages.success(self.request, f"{loan_type.capitalize()} loan application submitted successfully!")
                return redirect(self.success_url)
        except IntegrityError:
            messages.error(self.request, f"An unexpected error occurred while processing your {loan_type} loan application.")
            return redirect(self.success_url)

    def form_invalid(self, form):
        ''' Adding an error message '''
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"{error}")
                
        return render(self.request, self.template_name, {'personal_loan_form': form})
    
    def get_form_kwargs(self):
        """
        Pass additional kwargs to the form instance. Useful for passing the request object or other variables.
        """
        kwargs = super(PersonalLoanCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class LoanListView(ListView):
    model = Loan
    template_name = 'loans/loans_home.html'
    context_object_name = 'loans'  # context name to use in the template

    def get_queryset(self):
        """
        Override to return all loans (including specific types like HomeLoan and EducationLoan)
        for the currently logged-in user.
        """
        user = self.request.user
        loans = Loan.objects.filter(user=user).select_related('homeloan', 'educationloan')
        return loans


class PersonalLoanUpdateView(UpdateView):
    model = Loan
    form_class = LoanForm
    template_name = 'loans/loan_form.html'
    success_url = reverse_lazy('loan_list')  # Redirect to the loan list after update

    def form_valid(self, form):
        ''' Method is called when valid form data has been posted. '''
        response = super().form_valid(form)  # Saves the form instance
        return response


# =========================== Home Loan Views ===========================================
class HomeLoanCreateView(LoginRequiredMixin, FormView):
    template_name = 'loans/home_loan_form.html'
    form_class = HomeLoanForm
    success_url = reverse_lazy('loans:loan_home')  # Redirect to this URL after successful form submission

    def get(self, request):
        ''' 
        This method is called for GET requests
        '''
        if request.user.is_authenticated:
            home_loan_form = HomeLoanForm()
            return render(request, self.template_name, {'home_loan_form': home_loan_form})

    def form_valid(self, form):
        '''
            This method is called when valid form data has been POSTed.
        '''
        loan_type = 'home'
        existing_home_loans = Loan.objects.filter(user=self.request.user, loan_type=loan_type).exists()
        if existing_home_loans:
            # If an existing home loan is found, prevent the new loan application
            messages.error(self.request, "You've already taken a Home Loan and are not eligible for another home loan.")
            return redirect('loans:apply_home_loan')
        
        try:
            with transaction.atomic():
                form.instance.user = self.request.user
                form.save()  
                messages.success(self.request, f"{loan_type.capitalize()} loan application submitted successfully!")
                return HttpResponseRedirect(self.get_success_url())
        except IntegrityError:
            messages.error(self.request, f"An unexpected error occurred while processing your {loan_type} loan application.")
            return redirect('loans:apply_home_loan')
        
    def form_invalid(self, form):
        ''' Adding an error message for each form field that has an error '''
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"{error}")
                
        return render(self.request, self.template_name, {'home_loan_form': form})

    def get_form_kwargs(self):
        """
        Pass additional kwargs to the form instance. Useful for passing the request object or other variables.
        """
        kwargs = super(HomeLoanCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class HomeLoanUpdateView(LoginRequiredMixin, UpdateView):
    model = Loan
    form_class = HomeLoanForm
    template_name = 'loans/home_loan_update_form.html'
    success_url = reverse_lazy('loans:loan_home')

    def form_valid(self, form):
        messages.success(self.request, "Home Loan updated successfully!")
        return super().form_valid(form)

    def get_queryset(self):
        return Loan.objects.filter(user=self.request.user, loan_type='home')
    
# =========================== Education Loan Views ========================================
class EducationLoanCreateView(LoginRequiredMixin, FormView):
    template_name = 'loans/education_loan_form.html'
    form_class = EducationLoanForm
    success_url = reverse_lazy('loans:loan_home')  # Ensure this is the correct URL for redirect after success

    def get(self, request):
        ''' Handles GET requests '''
        if request.user.is_authenticated:
            education_loan_form = EducationLoanForm(user=request.user)
            return render(request, self.template_name, {'form': education_loan_form})

    # def form_valid(self, form):
    #     ''' Called when valid form data has been POSTed. Also redirect to success_url '''
    #     loan_type = 'education'
    #     existing_education_loans = Loan.objects.filter(user=self.request.user, loan_type=loan_type).exists()
    #     if existing_education_loans:

templates/loans/loan_home.html
{% extends 'core/base.html' %}
{% load static %}

{% block head_title %}Banking System{% endblock %}
{% block head %}{% endblock %}
{% block content %}
    <div class="container mx-auto px-4">
        <h1 class="mt-12 text-4xl font-bold text-center">Apply for a Loan</h1>
        <p class="text-center text-lg mt-2">Choose the type of loan you need, and let us help you make your dreams come
            true.</p>

        <div class="flex flex-wrap justify-center gap-4 mt-8">
            <div class="w-full md:w-1/3 bg-white shadow-md rounded-lg flex flex-col justify-between p-6">
                <div>
                    <h2 class="text-2xl font-semibold">Personal Loan</h2>
                    <p class="mt-3 text-gray-600">Whether it's for a vacation, a wedding, or unexpected expenses, our
                        personal loan offers competitive rates and flexible terms.</p>
                </div>
                <button
                        class="mt-4 w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Apply for Personal Loan
                </button>
            </div>
            <div class="w-full md:w-1/3 bg-white shadow-md rounded-lg flex flex-col justify-between p-6">
                <div>
                    <h2 class="text-2xl font-semibold">Home Loan</h2>
                    <p class="mt-3 text-gray-600">Buy your dream home with our affordable home loans, offering long
                        tenure and lower interest rates.</p>
                </div>
                <button onclick="location.href='{% url 'loans:apply_home_loan' %}'"
                        class="mt-4 w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Apply for Home Loan
                </button>
            </div>
            <div class="w-full md:w-1/3 bg-white shadow-md rounded-lg flex flex-col justify-between p-6">
                <div>
                    <h2 class="text-2xl font-semibold">Education Loan</h2>
                    <p class="mt-3 text-gray-600">Invest in your future with our education loans, designed to finance
                        higher studies with ease.</p>
                </div>
                <button onclick="location.href='{% url 'loans:apply_education_loan' %}'"
                        class="mt-4 w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Apply for Education Loan
                </button>
            </div>
        </div>

        <div class="mt-12">
            <h2 class="text-3xl font-semibold text-center">Customer Testimonials</h2>
            <div class="mt-6 space-y-4">
                <p class="bg-gray-100 p-4 rounded shadow">"Thanks to the personal loan from [Bank Name], I was able to
                    cover my emergency medical bills without any hassle." - Jane Doe</p>
                <p class="bg-gray-100 p-4 rounded shadow">"The home loan process was smooth and the staff was very
                    helpful throughout. Highly recommend!" - John Smith</p>
                <p class="bg-gray-100 p-4 rounded shadow">"Getting an education loan was quick and easy, which helped me
                    focus on my studies rather than the fees." - Emily Johnson</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/loans/loans_apply.html
{% extends 'core/base.html' %}
{% load static %}

{% block head_title %}Banking System{% endblock %}
{% block head %}{% endblock %}
{% block content %}
    <div class="container mx-auto px-4">
        <h1 class="mt-12 text-4xl font-bold text-center">Apply for a Loan</h1>
        <p class="text-center text-lg mt-2">Choose the type of loan you need, and let us help you make your dreams come
            true.</p>

        <div class="flex flex-wrap justify-center gap-4 mt-8">
            <div class="w-full md:w-1/3 bg-white shadow-md rounded-lg flex flex-col justify-between p-6">
                <div>
                    <h2 class="text-2xl font-semibold">Personal Loan</h2>
                    <p class="mt-3 text-gray-600">Whether it's for a vacation, a wedding, or unexpected expenses, our
                        personal loan offers competitive rates and flexible terms.</p>
                </div>
                <button onclick="location.href='{% url 'loans:apply_personal_loan' %}'"
                        class="mt-4 w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Apply for Personal Loan
                </button>
            </div>
            <div class="w-full md:w-1/3 bg-white shadow-md rounded-lg flex flex-col justify-between p-6">
                <div>
                    <h2 class="text-2xl font-semibold">Home Loan</h2>
                    <p class="mt-3 text-gray-600">Buy your dream home with our affordable home loans, offering long
                        tenure and lower interest rates.</p>
                </div>
                <button onclick="location.href='{% url 'loans:apply_home_loan' %}'"
                        class="mt-4 w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Apply for Home Loan
                </button>
            </div>
            <div class="w-full md:w-1/3 bg-white shadow-md rounded-lg flex flex-col justify-between p-6">
                <div>
                    <h2 class="text-2xl font-semibold">Education Loan</h2>
                    <p class="mt-3 text-gray-600">Invest in your future with our education loans, designed to finance
                        higher studies with ease.</p>
                </div>
                <button onclick="location.href='{% url 'loans:apply_education_loan' %}'"
                        class="mt-4 w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Apply for Education Loan
                </button>
            </div>
        </div>

        <div class="mt-12">
            <h2 class="text-3xl font-semibold text-center">Customer Testimonials</h2>
            <div class="mt-6 space-y-4">
                <p class="bg-gray-100 p-4 rounded shadow">"Thanks to the personal loan from SAFE Bank, I was able to
                    cover my emergency medical bills without any hassle." - Jane Doe</p>
                <p class="bg-gray-100 p-4 rounded shadow">"The home loan process was smooth and the staff was very
                    helpful throughout. Highly recommend!" - John Smith</p>
                <p class="bg-gray-100 p-4 rounded shadow">"Getting an education loan was quick and easy, which helped me
                    focus on my studies rather than the fees." - Emily Johnson</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/loans/loans_home.html
{% extends 'core/base.html' %}
{% load static %}

{% include 'core/messages.html' %}

{% block content %}
    <div class="container mx-auto mt-8">
        <h2 class="text-xl font-bold mb-2">Loan Details</h2>
        <!-- Button to apply for a new loan -->
        <div class="mb-2">
            <a href="{% url 'loans:apply_loan' %}"
               class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-3 rounded">
                Apply for New Loan
            </a>
        </div>
        {% for loan in loans %}
            <div class="bg-white shadow overflow-hidden sm:rounded-lg mb-2">
                <div class="px-4 py-3">
                    <div class="grid grid-cols-3 gap-2 items-center">
                        <!-- Column 1: Loan ID -->
                        <div>
                            <h3 class="text-lg font-semibold text-gray-900">Loan ID: {{ loan.pk }}</h3>
                        </div>
                        <!-- Column 2: Loan Type -->
                        <div>
                            <h3 class="text-lg font-semibold text-gray-900 uppercase">{{ loan.loan_type }} loan</h3>
                        </div>
                        <!-- Column 3: Loan Status with Dynamic Color -->
                        <div class="text-lg font-bold text-white py-1 px-3 rounded"
                             style="background-color: {% if loan.status == 'Approved' %}#10b981{% elif loan.status == 'Declined' %}#ef4444{% else %}#facc15{% endif %};">
                            Status: {{ loan.status }}
                        </div>
                    </div>
                </div>

                <div class="border-t border-gray-200">
                    <dl>
                        <div class="px-4 py-3 grid grid-cols-4 gap-2">
                            <div class="text-sm font-medium text-gray-500">Amount:</div>
                            <div class="mt-1 text-sm text-gray-900">${{ loan.amount }}</div>

                            <div class="text-sm font-medium text-gray-500">Interest Rate:</div>
                            <div class="mt-1 text-sm text-gray-900">{{ loan.interest_rate }}%</div>

                            <div class="text-sm font-medium text-gray-500">Tenure:</div>
                            <div class="mt-1 text-sm text-gray-900">{{ loan.tenure }} months</div>

                            <div class="text-sm font-medium text-gray-500">EMI Amount:</div>
                            <div class="mt-1 text-sm text-gray-900">${{ loan.emi_amount }}</div>
                        </div>

                        {% if loan.loan_type == 'home' %}
                            <!-- Grid for Home Loan Details Cards -->
                            <div class="grid grid-cols-1 sm:grid-cols-2 gap-2 px-4 py-3">
                                <!-- House Details Card -->
                                <div class="bg-white rounded-lg shadow p-3">
                                    <h3 class="text-lg font-semibold text-gray-800">House Details:</h3>
                                    <ul class="mt-1 text-sm text-gray-700 list-disc list-inside">
                                        <li>Year Built: {{ loan.homeloan.house_built_year }}</li>
                                        <li>Insurance Company: {{ loan.homeloan.insurance.company }}</li>
                                        <li>Insurance Premium: ${{ loan.homeloan.insurance.premium }}</li>
                                    </ul>
                                </div>

                                <!-- Home Loan Address Card, now with grid layout -->
                                <div class="bg-white rounded-lg shadow p-3">
                                    <h3 class="text-lg font-semibold text-gray-800">Home Loan Address:</h3>
                                    <div class="grid grid-cols-2 gap-1 mt-1 text-sm text-gray-700">
                                        <div>Street:</div>
                                        <div>{{ loan.homeloan.home_address.street }}</div>
                                        <div>City:</div>
                                        <div>{{ loan.homeloan.home_address.city }}</div>
                                        <div>State:</div>
                                        <div>{{ loan.homeloan.home_address.state }}</div>
                                        <div>Country:</div>
                                        <div>{{ loan.homeloan.home_address.country }}</div>
                                        <div>ZIP:</div>
                                        <div>{{ loan.homeloan.home_address.zip_code }}</div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}

                        {% if loan.loan_type == 'education' %}
                            <!-- Grid for Education Loan Details Cards -->
                            <div class="grid grid-cols-1 sm:grid-cols-2 gap-2 px-4 py-3">
                                <!-- Education Details Card -->
                                <div class="bg-white rounded-lg shadow p-3">
                                    <h3 class="text-lg font-semibold text-gray-800">Education Details:</h3>
                                    <ul class="mt-1 text-sm text-gray-700 list-disc list-inside">
                                        <li>University: {{ loan.educationloan.university.name }}</li>
                                        <li>Degree: {{ loan.educationloan.degree }}</li>
                                        <li>Graduation
                                            Date: {{ loan.educationloan.graduation_date | date:"Y-m-d" }}</li>
                                    </ul>
                                </div>

                                <!-- Student Personal Information Card -->
                                <div class="bg-white rounded-lg shadow p-3">
                                    <h3 class="text-lg font-semibold text-gray-800">Student Information:</h3>
                                    <div class="grid grid-cols-2 gap-1 mt-1 text-sm text-gray-700">
                                        <div>First Name:</div>
                                        <div>{{ loan.educationloan.student_info.first_name }}</div>
                                        <div>Last Name:</div>
                                        <div>{{ loan.educationloan.student_info.last_name }}</div>
                                        <div>Date of Birth:</div>
                                        <div>{{ loan.educationloan.student_info.date_of_birth | date:"Y-m-d" }}</div>
                                        <div>Email:</div>
                                        <div>{{ loan.educationloan.student_info.email }}</div>
                                        <div>Phone:</div>
                                        <div>{{ loan.educationloan.student_info.phone }}</div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </dl>
                </div>
            </div>
        {% empty %}
            <div class="bg-white shadow overflow-hidden sm:rounded-lg p-3">
                <p>No loans found.</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/loans/personal_loan_form.html
{% extends 'core/base.html' %}
{% load static %}

{% block head_title %}
    Apply for a Personal Loan
{% endblock %}

{% block content %}
    <div class="max-w-4xl mx-auto bg-white p-8 mt-10 shadow-lg rounded-lg border">
        <h2 class="text-center text-2xl font-semibold text-gray-800 mb-6">Apply for a Personal Loan</h2>
        <form method="post" class="space-y-6">
            {% csrf_token %}
            <!-- Loan Information Card -->
            <div class="bg-gray-100 p-5 rounded-md shadow">
                <h3 class="text-lg font-semibold mb-4">Loan Information</h3>
                <div class="grid grid-cols-2 gap-4">
                    <label for="amount" class="font-medium text-gray-700">Loan Amount:</label>
                    {{ personal_loan_form.amount }}
                    <label for="tenure" class="font-medium text-gray-700">Loan Tenure:</label>
                    {{ personal_loan_form.tenure }}
                </div>
            </div>
            <button type="submit"
                    class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded focus:outline-none focus:shadow-outline">
                Submit Application
            </button>
        </form>
    </div>
{% endblock %}